[package]
name = "scraper_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "rustls-tls", "cookies"] }
tokio = { version = "1", features = ["full"] }
scraper = "0.13"
dashmap = "5.0"
url = "2.5.2"
log = "0.4"
env_logger = "0.11.5"